on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: azure/docker-login@v1
      with:
        login-server: manjeetazacr.azurecr.io
        username: ${{ secrets.acr_manjeetazacr_username }}
        password: ${{ secrets.acr_manjeetazacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t manjeetazacr.azurecr.io/manjeetaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push manjeetazacr.azurecr.io/manjeetaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_manjeetaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep devs | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace devs`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: devs
        container-registry-url: manjeetazacr.azurecr.io
        container-registry-username: ${{ secrets.acr_manjeetazacr_username }}
        container-registry-password: ${{ secrets.acr_manjeetazacr_password }}
        secret-name: manjeetaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: devs
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          manjeetazacr.azurecr.io/manjeetaks:${{ github.sha }}
        imagepullsecrets: |
          manjeetaksdockerauth
